import os
import re
import shutil
import win32com.client

# Target directory paths
script_dir = os.path.dirname(os.path.abspath(__file__))
combined_html_path = os.path.join(script_dir, "combined_output.html")
temp_html_path = os.path.join(script_dir, "temp_export.html")

TOTAL_FILES = 259

# Start Word COM engine once
word = win32com.client.Dispatch("Word.Application")
word.Visible = False

try:
    with open(combined_html_path, "w", encoding="utf-8") as output_file:
        # Write HTML head wrapper
        output_file.write('<!DOCTYPE html>\n<html lang="en">\n<head>\n')
        output_file.write('<meta charset="UTF-8">\n')
        output_file.write('<title>Combined Output</title>\n')
        output_file.write('</head>\n<body>\n')

        for i in range(1, TOTAL_FILES + 1):
            file_name = f"Large numbers volume {i}.docx"
            docx_path = os.path.join(script_dir, file_name)

            if not os.path.exists(docx_path):
                print(f"Skipping (not found): {file_name}")
                continue

            print(f"Processing ({i}/{TOTAL_FILES}): {file_name}...")

            # 1. Export as UTF-8 Filtered HTML
            doc = word.Documents.Open(docx_path)
            doc.WebOptions.Encoding = 65001  # msoEncodingUTF8 (preserves '¬' and math symbols)
            doc.SaveAs2(temp_html_path, FileFormat=10)  # 10 = wdFormatFilteredHTML
            doc.Close()

            # 2. Read full document HTML content
            with open(temp_html_path, "r", encoding="utf-8") as f:
                html_content = f.read()

            # 3. Extract content inside <body>...</body> to merge cleanly without duplicate head tags
            body_match = re.search(r'<body[^>]*>(.*?)</body>', html_content, flags=re.DOTALL | re.IGNORECASE)
            if body_match:
                inner_body = body_match.group(1).strip()
            else:
                inner_body = html_content  # Fallback if body tag is missing

            # Append document content directly to final HTML file
            output_file.write(f'<!-- Start: {file_name} -->\n')
            output_file.write(inner_body)
            output_file.write(f'\n<!-- End: {file_name} -->\n\n')

            # Flush write buffer to disk to keep RAM lightweight
            output_file.flush()

            # Clean up temporary HTML file and asset folder generated by Word
            if os.path.exists(temp_html_path):
                os.remove(temp_html_path)

            temp_files_folder = os.path.join(script_dir, "temp_export_files")
            if os.path.exists(temp_files_folder):
                shutil.rmtree(temp_files_folder, ignore_errors=True)

        # Close HTML wrapper
        output_file.write('</body>\n</html>\n')

finally:
    word.Quit()

print(f"\nSuccessfully generated {combined_html_path}!")